### ISSUE TITLE
VCDB Triplet Generation

### ISSUE THREAD

**Issue by chqaqc** [MKLab-ITI/ndvr-dml#17]
Error ：
CC_WEB_VIDEO Triplet Generation
===============================
Query 0:   0%|          | 0/341 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "triplet_generator.py", line 186, in <module>
    triplets = triplet_generator_cc(dataset, features)
  File "triplet_generator.py", line 141, in triplet_generator_cc
    pair_distance = euclidean(video1, video2)
  File "/home/chq/anaconda3/envs/python2/lib/python2.7/site-packages/scipy/spatial/distance.py", line 602, in euclidean
    return minkowski(u, v, p=2, w=w)
  File "/home/chq/anaconda3/envs/python2/lib/python2.7/site-packages/scipy/spatial/distance.py", line 505, in minkowski
    dist = norm(u_v, ord=p)
  File "/home/chq/anaconda3/envs/python2/lib/python2.7/site-packages/scipy/linalg/misc.py", line 145, in norm
    return nrm2(a)
_fblas.error: (offx>=0 && offx<len(x)) failed for 2nd keyword offx: dnrm2:offx=0

occurs when I run triplet_generator.py, do you know why? And only generates cc_web_video_features.npy
without cc_web_video_triplets.npy
thanks!

**Comment by gkordo** [comment]
It seems like it's an issue of scikit-learn and blas. Try to update/reinstall these two packages:
```
conda install -c anaconda scikit-learn blas
```
or create a new environment in conda and run the code from that.
Also, make sure that the generated array `cc_web_video_features.npy` is not all zeros.
